name: cryptex_aer
description: Z-KINETIC Security Suite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Security Guards & Core ---
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  http: ^1.2.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  
  # --- Sensors & Storage ---
  sensors_plus: ^3.0.0
  shared_preferences: ^2.2.0
  
  # --- Database & Utilities ---
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
