name: z_kinetic_pro
description: Military-grade biometric security suite
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ FIREBASE (VERSI STABIL 3.x)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  firebase_app_check: ^0.3.1+4
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_remote_config: ^5.1.3
  
  # ðŸ‘‡ INI YANG KITA TAMBAH BALIK SEBAB KOD TUAN CARI DIA
  cloud_functions: ^5.1.3 

  # ðŸ” UTILITIES
  uuid: ^4.5.1
  crypto: ^3.0.5
  intl: ^0.19.0
  encrypt: ^5.0.3

  # ðŸ“± SENSORS
  sensors_plus: ^6.0.0
  device_info_plus: ^11.0.0
  package_info_plus: ^8.0.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0
  http: ^1.2.2
  path_provider: ^2.1.4

  # ðŸ’¾ DATABASE
  sqflite: ^2.4.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
    - assets/metal_wheel.png

dependency_overrides:
  web: ^1.1.0
  firebase_core_web: ^2.18.1

