dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sensors_plus: ^5.0.0
  shared_preferences: ^2.2.0
  flutter_jailbreak_detection: ^1.1.0
  # --- SENJATA BARU ---
  vibration: ^1.8.4        # Untuk getaran premium
  flutter_secure_storage: ^9.0.0 # Untuk peti besi rahsia
