name: cryptex_aer
description: Secure Biometric Authentication System by Captain Aer.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sensors_plus: ^5.0.0
  shared_preferences: ^2.2.0
  flutter_jailbreak_detection: ^1.1.0
  flutter_secure_storage: ^9.0.0
  
  # âœ¨ TAMBAH 3 DEPENDENCIES NI:
  crypto: ^3.0.3
  device_info_plus: ^9.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true




